# Generated by Django 4.2 on 2026-04-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('savings', 'Savings'), ('salary', 'Salary')], default='cash', max_length=20),
        ),
    ]
