# Generated by Django 4.2 on 2026-04-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_expense_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('BALANCE', 'Balance')], default='EXPENSE', max_length=10),
        ),
        migrations.AddField(
            model_name='category',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('savings', 'Savings'), ('salary', 'Salary')], default='cash', max_length=20),
        ),
    ]
